name: Check website

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository files
        uses: actions/checkout@v4

      - name: Build website
        uses: actions/jekyll-build-pages@v1

      - name: Save website preview
        uses: actions/upload-artifact@v4
        with:
          name: website-preview
          path: _site/
